#input and output file names
input file location: histos/SS_ttW_studies_2t_lepCut
input file label: ttV_SS_Nov14
output file location: pdf/SS_ttW_studies_2t_lepCut

#drawing options
skip systematics: true
draw ratio plot: true
draw legend: true
log scale: false
save png: true
save pdf: true
blinded: true
KS test: false
selection info : false
SF info: false

#luminosity and era
luminosity: 19.5
luminosity error: 0.044
trigger SF error: 0.02
lumi era string: "                #sqrt{s} = 8 TeV, L = 19.5 fb^{-1}"

#Lepton categories: "draw name"
lepton categories:
    mu_mu:
        data samples: [DoubleMu]
        excluded samples: []
        tex name: " #mu #mu "
    mu_ele:
        data samples: [MuEG]
        excluded samples: []
        tex name: " #mu e "
    ele_ele:
        data samples: [DoubleElectron]
        excluded samples: []
        tex name: " e e "


#Jet-tag categories: "draw name"
jet tag categories:
#     eq2j: " + 2 jets"
#     eq3j: " + 3 jets"
#     ge4j: " + #geq4 jets"
#     eq2j_metLD: " + 2 jets + metLD"
#     eq3j_metLD: " + 3 jets + metLD"
#     ge4j_metLD: " + #geq4 jets + metLD"
#     eq2j_bloose: " + 2 jets + bloose"
#     eq3j_bloose: " + 3 jets + bloose"
#     ge4j_bloose: " + #geq4 jets + bloose"
#     eq2j_metLD: " + 2 jets + metLD + bloose"
#     eq3j_metLD: " + 3 jets + metLD + bloose"
#     ge4j_metLD: " + #geq4 jets + metLD + bloose"

#     ge4j_ttH: " + #geq4 jets + ttH selection"

#     ttbar: " + ttbar selection"
#     ttbar_high_BDT: " + ttbar high BDT"

#     eq0j: " + 0 jets"
#     eq1j: " + 1 jets"
#     eq2j: " + 2 jets"
#     eq3j_lf: " + 3 jets + lf"
#     ge4j_lf: " + #geq4 jets + lf"
    eq3j_bloose: " + 3 jets + bloose"
    ge4j_bloose: " + #geq4 jets + bloose"
    
#     ge0j_Zpeak: " + #geq0 jets"
# #     eq0j_Zpeak: " + 0 jets"
# #     eq1j_Zpeak: " + 1 jets"
# #     eq2j_Zpeak: " + 2 jets"
    
#Systematics used in error bars
systematics:
    - nominal
    - weight_PUUp
    - weight_PUDown
    - topPtWgtDown
    - topPtWgtUp
    - csvWeightHFUp
    - csvWeightHFDown
    - csvWeightLFUp
    - csvWeightLFDown
    
# Samples drawn on top, scaling (1.0, 2.0, "norm" for area-normalized) 
signal samples:
    ttW:
        draw name: "t#bar{t}W"
        #color: kGreen-5
        color: kBlue
        samples: [ttbarW]
        stack or line: line
        line width: 2 # must be integer
        scale: "norm"

#Samples in each group will be added together and appear as a single entry in the stack plot
background samples:
#     inclusive_data_NP_sideband:
#         draw name: "Fakes"
#         color: kGray
#         systematics: [40PercentRateUp, 40PercentRateDown]
#         samples: [inclusive_data_NP_sideband]

    DoubleMu_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [DoubleMu_NP_sideband]

    MuEG_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [MuEG_NP_sideband, MuEG_QF_sideband_neg]
        #samples: [MuEG_NP_sideband]

    DoubleElectron_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [DoubleElectron_NP_sideband, DoubleElectron_QF_sideband_neg]
        #samples: [DoubleElectron_NP_sideband]

    MuEG_QF_sideband:
        draw name: "Q flip"
        color: kGray+1
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [MuEG_QF_sideband]

    DoubleElectron_QF_sideband:
        draw name: "Q flip"
        color: kGray+1
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [DoubleElectron_QF_sideband]

    wz_lll:
        draw name: "WZ"
        color: kViolet-4
        samples: [wz_lll]
        
    zz_llll:
        draw name: "ZZ"
        color: kAzure-9
        samples: [zz_llll]
        
#     zz_lowmll:
#         draw name: "ZZ*"
#         color: kAzure-8
#         samples: [zz_lowmll]
        
    multiboson:
        draw name: "multiboson"
        color: kViolet
        samples: [www, wwz, WpWpqq, WWDPI] #wzz, zzz, WmWmqq

    ttbarX:
        draw name: "t#bar{t}+X"
        color: kSpring+8
        samples: [tbZ_ll, ttbarG, ttbarGStar_ee, ttbarGStar_mm, ttbarGStar_tt, ttbarWW]

    ttH125:
        draw name: "t#bar{t}H"
        color: kRed
        samples: [ttH125]
                                        
    ttbarZ:
        draw name: "t#bar{t}Z"
        color: kSpring+2
        samples: [ttbarZ]
                                        
    ttbarW:
        draw name: "t#bar{t}W"
        color: kGreen-5
        samples: [ttbarW]

#     ttbar_lj:
#         draw name: ttbar_lj
#         color: kGray
#         samples: [ttbar_lj]

#     ttbar_ll:
#         draw name: ttbar_ll
#         color: kGray+1
#         samples: [ttbar_ll]

#     Zjets:
#         draw name: Zjets
#         color: kBlue
#         samples: [zjets_0p, zjets_1p, zjets_2p, zjets_3p, zjets_4p]

#distribution: [title, underflow, overflow]
distributions:
    numAllLeptons: [number of leptons, false, false]
    numAllMuons: [number of muons, false, false]
    numJets: ['number of jets', false, false]
    numLooseBJets: ['number of loose b-tagged jets', false, false]
    numMediumBJets: ['number of medium b-tagged jets', false, false]
    all_leptons_by_pt_1_pt: ['First lepton pT', false, false]
    all_leptons_by_pt_2_pt: ['Second lepton pT', false, false]
    #NP_lepton_pt: ['NP lepton pT', false, true]
    all_leptons_by_pt_1_eta: ['First lepton eta', false, false]
    all_leptons_by_pt_2_eta: ['Second lepton eta', false, false]
    max_lepton_eta: ['Max lepton eta', false, false]
    #NP_lepton_eta: ['NP lepton eta', false, false]
    #all_leptons_by_pt_1_jetBTagCSV: ['First lepton jetBTagCSV', true, false]
    #all_leptons_by_pt_2_jetBTagCSV: ['Second lepton jetBTagCSV', true, false]
    #max_lepton_jetBTagCSV: ['max lepton jetBTag CSV', true, false]
    #NP_lepton_jetBTagCSV: ['NP lepton jetBTag CSV', true, false]
    jets_by_pt_1_pt: ['First jet pT', false, false]
    jets_by_pt_2_pt: ['Second jet pT', false, false]
    min_mass_leplep: ['Min dilepton mass', false, false]
    mass_lep1_lep2: ['Mass lep1-lep2', false, false]
    met_pt: ['MET', false, true]
    mht: ['MHT', false, true]
    met_ld: ['MetLD', false, true]
    #sum_pt: ['Sum pT', true, true]
    #sum_jet_pt: ['Sum jet pT', false, true]
    #mass_of_jets: ['Mass of all jets', false, true]
    #jets_MT_mass_ratio: ['MT/mass of all jets', false, false]
    #everything_MT_mass_ratio: ['MT/mass of everything', false, false]
    MT_of_everything: ['MT of everything', true, true]
    ttbar_fake_SS_top_MT_met_lep_B: ['ttbar fake leptonic top MT', true, true]
    ttbar_fake_SS_top_mass_blep_qq: ['ttbar fake hadronic top mass', true, true]
    jets_by_CSV_2_btagCombinedSecVertex: ['second highest jet CSV', true, true]
    #Match_ttbar_fake_SS_Bq: ['match score ttbar Bq', true, true]
    Match_ttbar_fake_SS_Bqq: ['match score ttbar Bqq', true, true]
    #Match_ttW_SS_Bb: ['match score ttW Bb', true, true]
    #Match_ttW_SS_Bq: ['match score ttW Bq', true, true]
    #Match_ttW_SS_bq: ['match score ttW bq', true, true]
    Match_ttW_SS_Bbq: ['match score ttW Bbq', true, true]
    Match_ttW_SS_Bqq: ['match score ttW Bqq', true, true]
    Match_ttW_SS_Bbqq: ['match score ttW Bbqq', true, true]
    FinalBDT_QCD: ['final BDT vs. QCD', false, false]
    FinalBDT: ['final BDT', false, false]
    FinalBDT_Oct31: ['final BDT Oct 31', false, false]
    #FinalBDT_blind: ['final BDT', false, false]
    #FinalBDT_Oct31_blind: ['final BDT Oct 31', false, false]
    
