#input and output file names
input file location: ../histos/4l_ttZ_studies_4l_lepCut_forLimits
input file label: ttV_Nov14

lepton categories:
    4l:
        data sample: inclusive_data
        excluded samples: [] #[ttbarG]
        category name: 'ttZ_4l'
        
#Jet-tag categories: "draw name"
jet tag categories:
    ge1j_Zpeak_mht30_1bloose: ""
    ge1j_Zmask_mht30_1bloose: ""
    
    #ge1j_Zpeak_mht30_ge1t: ""
    #ge1j_Zmask_mht30_ge1t: ""
    

#Systematics used in error bars
systematics:
    - nominal
    - JES
    - weight_PU
    - topPtWgt
    - csvWgtlf_HF
    - csvWgtlf_Stats1
    - csvWgtlf_Stats2
    - csvWgthf_LF
    - csvWgthf_Stats1
    - csvWgthf_Stats2
    - csvWgtc_Err1
    - csvWgtc_Err2

ttH mass points: ##New code to automate masses
    - '125'
    
data samples:
    inclusive_data:
        datacard name: "data_obs"
        systematics: none
        samples: [inclusive_data]

signal samples:
    ttbarZ:
        datacard name: "TTZ"
        systematics: common
        samples: [ttbarZ]
        scale: 1.0

#Samples, ordered bottom-to-top
background samples:
#     inclusive_data_NP_sideband:
#         datacard name: "FR_data"
#         systematics: none
#         samples: [inclusive_data_NP_sideband]
#         scale: 1.0

#     inclusive_data_NP_sideband_2:
#         datacard name: "FR2_data"
#         systematics: none
#         samples: [inclusive_data_NP_sideband_2]
#         scale: 1.0

    ttbar_ll:
        datacard name: "FR_TTJets"
        systematics: common
        samples: [ttbar_ll]

    wz_lll:
        datacard name: "FR_WZ"
        systematics: common
        samples: [wz_lll]
        
#     zz_llll:
#         datacard name: "ZZ"
#         systematics: common
#         samples: [zz_llll]

    zz_lf_llll:
        datacard name: "ZZ_LF"
        systematics: common
        samples: [zz_lf_llll]
        
    zz_cc_llll:
        datacard name: "ZZ_CC"
        systematics: common
        samples: [zz_cc_llll]

    zz_b_llll:
        datacard name: "ZZ_B"
        systematics: common
        samples: [zz_b_llll]
        
    zz_bb_llll:
        datacard name: "ZZ_2B"
        systematics: common
        samples: [zz_bb_llll]

    triboson:
        datacard name: "VVV"
        systematics: common
        samples: [wwz] #wzz, zzz
 
    ttbarG:
        datacard name: "TTG"
        systematics: common
        samples: [ttbarG]

    ttbarGStar:
        datacard name: "TTStarG"
        systematics: common
        samples: [ttbarGStar_ee, ttbarGStar_mm, ttbarGStar_tt]

    ttbarWW:
        datacard name: "TT2W"
        systematics: common
        samples: [ttbarWW]

#     ttbarX:
#         datacard name: "TTX"
#         systematics: common
#         samples: [ttbarG, ttbarGStar_ee, ttbarGStar_mm, ttbarGStar_tt, ttbarWW]
#         scale: 1.0

    ttbarH:
        datacard name: "TTH"
        systematics: common
        samples: [ttH125]
        scale: 1.0

